/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Prime {
    public boolean isPrime(int n) {
        return n % 2 != 0;
    }

    public static void main(String[] args) {
    }
}
